services:
  db:
    image: postgres:15
    restart: always
    container_name: printmaster
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wsCbjEzwguDWesEosLSYRJoFnIAJqvqe
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    driver: local