services:
  db:
    image: postgres:15
    restart: always
    container_name: printmaster_db
    environment:
      POSTGRES_DB: printmasterdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LkddIOkSGlZgnMhlbzFqavZFjpVtSBZt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    driver: local