spring:
  application:
    name: PrintMasterCRM
  datasource:
    url: jdbc:postgresql://junction.proxy.rlwy.net:30722/railway
    username: postgres
    password: LkddIOkSGlZgnMhlbzFqavZFjpVtSBZt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    clean-disabled: false
