CREATE TABLE account_roles
(
    account_id BIGINT       NOT NULL,
    roles      VARCHAR(255) NOT NULL
);

CREATE TABLE accounts
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         VARCHAR(255)                            NOT NULL,
    phone_number     VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    manager_username VARCHAR(255),
    account_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE "order"
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id     BIGINT                                  NOT NULL,
    manager_id      BIGINT                                  NOT NULL,
    product         VARCHAR(255)                            NOT NULL,
    postpress_price DECIMAL                                 NOT NULL,
    total_cost      DECIMAL                                 NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE printing
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    papier   VARCHAR(255),
    colour   VARCHAR(255),
    quantity INTEGER                                 NOT NULL,
    order_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_printing PRIMARY KEY (id)
);

CREATE TABLE stamping
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity                      INTEGER                                 NOT NULL,
    one_ottisk_price              DECIMAL,
    montage_work_price            DECIMAL,
    one_quadrat_metter_foil_price DECIMAL,
    widthsm                       DOUBLE PRECISION                        NOT NULL,
    lengthsm                      DOUBLE PRECISION                        NOT NULL,
    order_id                      BIGINT                                  NOT NULL,
    CONSTRAINT pk_stamping PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_name UNIQUE (name);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_username UNIQUE (username);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_email UNIQUE (email);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_phonenumber UNIQUE (phone_number);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_username UNIQUE (username);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES accounts (id);

ALTER TABLE printing
    ADD CONSTRAINT FK_PRINTING_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE stamping
    ADD CONSTRAINT FK_STAMPING_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE account_roles
    ADD CONSTRAINT fk_account_roles_on_account FOREIGN KEY (account_id) REFERENCES accounts (id);